### PR TITLE
Fixed Delphinus support

### PR DESCRIPTION
**Pull request by Pawe1**
Delphinus support didn't work at all so I fixed it.
I made some testing on 10.2.

You should also add a tag **1.2.0** to mark release version.

Regards
P.

### CODE REVIEW

**Comment by rfrezino** [comment]
Thank you for that!

**Comment by Pawe1** [comment]
oh... I figured out that making tags visible as release on GitHub requires few more clicks...

1.


2.


3.

**Comment by rrezino** [comment]
Just create the version 1.2.0 based on a git tag. 
So far I can't see it on Delphinus, I don't know if there is a delay.

**Comment by Pawe1** [comment]
There shouldn't be any delay...
Something more is probably missing - i'll try to investigate.

**Comment by Pawe1** [comment]
I have no idea why but GitHub API have some problems with including this repository in search results...

https://api.github.com/search/repositories?q="Delphinus-Support"+in:readme&per_page=100 => nothing

https://api.github.com/search/repositories?q="RFindUnit"&per_page=100 => this is ok

https://api.github.com/search/repositories?q="Rodrigo%20Farias%20Rezino"+in:readme&per_page=100 => look at this! There should be more results...

Any idea?
Are there any custom settings for repository?

**Comment by Pawe1** [comment]
I've sent a request to GitHub...

**Comment by Pawe1** [comment]
Gotcha!
I've found the cause - `</br>` tags in README.md

https://github.com/rfrezino/RFindUnit/pull/70

PS. Are You sure that Find Unit works with older Delphi versions than Seattle? (10.0)

**Comment by Pawe1** [comment]
**Tadaaa!**

untitled

**Comment by Pawe1** [comment]
One last thing - **You should move 1.2.0 tag to some newer commit** because `HEAD` version works but Installing Delphinus from `1.2.0` causes error (because tag 1.2.0 is in history before fixes)

untitled

**Pull request merged**
